"""
backend/main.py
────────────────
FastAPI application entrypoint for the
"Real-Time Incident Tracking & Autonomous Threat Remediation" system.

Run locally with:
    uvicorn backend.main:app --reload

Or from the project root with explicit host/port:
    uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs          ← Swagger UI
    http://localhost:8000/redoc         ← ReDoc
"""

from __future__ import annotations

import logging
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# ── Internal imports ──────────────────────────────────────────────────────────
from backend.db.database import check_db_connection
from backend.db.init_db import init_db
from backend.routers import connection_route, health_route, incident_route, predict_route

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger(__name__)

_START_TIME = time.monotonic()


# ── Lifespan (startup + shutdown) ─────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Application lifespan context manager.

    *Startup*:
      1. Check DB connectivity and print result.
      2. Create all tables (idempotent) and list them.
      3. Attempt to load ML artefacts via inference.load_models().

    *Shutdown*:
      • Print uptime and exit cleanly.
    """
    import sys                                             # noqa: PLC0415
    from backend.db.database import DATABASE_URL, engine  # noqa: PLC0415
    from backend.db.database_models import Incident                 # noqa: F401,PLC0415
    from sqlalchemy import inspect as sa_inspect           # noqa: PLC0415

    # Reconfigure stdout to UTF-8 so emoji/box chars work on Windows terminals.
    # Falls back silently if the stream does not support reconfigure().
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    SEP = "=" * 55

    print(f"\n{SEP}")
    print("  IDS API - startup diagnostics")
    print(SEP)

    # ── 1. Database connectivity ──────────────────────────────────
    print(f"\n[DB] Connecting to: {DATABASE_URL}")
    db_ok = check_db_connection()
    if db_ok:
        print("[DB] [OK] PostgreSQL is UP - connection successful")
    else:
        print("[DB] [!!] PostgreSQL is DOWN - start it with:  docker compose up -d")
        print("[DB]      The API will still start but DB endpoints will fail.")

    # -- 2. Table creation ------------------------------------------------
    print("\n[DB] Creating tables (if they do not already exist)...")
    tables_created: list[str] = []
    try:
        init_db()                             # calls Base.metadata.create_all()

        # Inspect the engine to list every table that now exists
        inspector = sa_inspect(engine)
        existing_tables = inspector.get_table_names()
        tables_created = existing_tables

        if existing_tables:
            print(f"[DB] [OK] Tables ready ({len(existing_tables)} total):")
            for tbl in existing_tables:
                cols = [c["name"] for c in inspector.get_columns(tbl)]
                print(f"         + {tbl}  ({len(cols)} columns: {', '.join(cols)})")
        else:
            print("[DB] [??] No tables found after init_db() - check ORM models.")

    except Exception as exc:  # noqa: BLE001
        print(f"[DB] [!!] Table creation failed: {exc}")
        print("[DB]      Is PostgreSQL running?  docker compose up -d")

    # -- 3. ML model loading ----------------------------------------------
    print("\n[ML] Loading model artefacts...")
    try:
        import backend.inference as _inf  # noqa: PLC0415

        _inf.load_models()
        if _inf.autoencoder_ready and _inf.dqn_ready:
            print("[ML] [OK] Autoencoder + DQN agent loaded and ready")
        else:
            print("[ML] [--] Models NOT loaded - POST /predict will return HTTP 503")
            print("[ML]      Train models first; artefacts expected at:")
            print("[ML]        models/autoencoder.pt")
            print("[ML]        models/dqn_agent.pt")
            print("[ML]        models/scaler.pkl")
            print("[ML]        models/threshold.json")
    except Exception as exc:  # noqa: BLE001
        print(f"[ML] [!!] load_models() error: {exc}")

    # -- Summary banner ---------------------------------------------------
    print(f"\n{SEP}")
    status_db  = "[OK] UP  " if db_ok else "[!!] DOWN"
    status_tbl = f"{len(tables_created)} table(s)" if tables_created else "none / error"
    print(f"  DB connection : {status_db}")
    print(f"  Tables ready  : {status_tbl}")
    print(f"  Docs UI       : http://127.0.0.1:8000/docs")
    print(f"  WS alerts     : ws://127.0.0.1:8000/ws/connect")
    print(f"{SEP}\n")

    logger.info("IDS API ready — uptime clock started.")

    yield  # ← application runs here

    # ── Shutdown ──────────────────────────────────────────────────
    elapsed = time.monotonic() - _START_TIME
    print(f"\n[IDS API] Shutting down after {elapsed:.1f}s of uptime.")
    logger.info("IDS API shutting down after %.1f seconds of uptime.", elapsed)


# ── Application factory ───────────────────────────────────────────────────────
app = FastAPI(
    title="Real-Time Incident Tracking & Autonomous Threat Remediation",
    version="0.1.0",
    description=(
        "An AI-powered Network Intrusion Detection System (IDS) that combines "
        "a deep-learning autoencoder (anomaly detection) with a DQN reinforcement "
        "learning agent (autonomous remediation).  "
        "\n\n"
        "**WebSocket alerts**: connect to `ws://<host>/ws/alerts` to receive "
        "real-time JSON payloads whenever an anomaly is detected."
    ),
    contact={
        "name": "IISC Research Internship — IDS Pipeline",
    },
    lifespan=lifespan,
)


# ── CORS ──────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",    # React dev server (default CRA / Vite port)
        "http://localhost:5173",    # Vite alternative port
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(health_route.router)
app.include_router(incident_route.router)
app.include_router(predict_route.router)
app.include_router(connection_route.router)


# ── Root redirect ─────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
def root():
    """Redirect browsers hitting the root path to the interactive API docs."""
    from fastapi.responses import RedirectResponse  # noqa: PLC0415
    return RedirectResponse(url="/docs")
